host: localhost
port: 8585
hooks:
    test: http://192.168.99.100:8065/hooks/877tfk5y4byizc5bifini4u1yr
metrics: true
debug: true
dumpdir: dump
mmicon: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Puppeter_template.svg/40px-Puppeter_template.svg.png"
mmuser: "JIRA"
profile: "cpu"
profiledir: "."
