host: localhost
port: 8585
hooks:
    Test: http://192.168.99.100:8065/hooks/qqtsiqdjub8ijx696bwrzaqc1o
metrics: true
debug: true
dumpdir: dump
mmicon: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Puppeter_template.svg/40px-Puppeter_template.svg.png"
mmuser: "JIRA"
profile: "cpu"
profiledir: "."
